version: "3.7"
networks:
    laravel:
services:
    nginx:
        image: nginx:stable-alpine
        container_name: nginx
        ports:
            -   "8089:80"
        volumes:
            -   ./src:/var/www/html
            -   ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            -   php
            -   mysql
        networks:
            - laravel
    mysql:
        image: mysql:8.0
        container_name: mysql
        restart: unless-stopped
        tty: true
        ports:
            -   "4306:3306"
        volumes:
            -   ./mysql:/var/lib/mysql
        environment:
            MYSQL_DATEBASE: laravel_survey
            MYSQL_USER: root
            MYSQL_PASSWORD: 123456
            MYSQL_ROOT_PASSWORD: 123456
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks:
            - laravel
    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: php
        volumes:
            -   ./src:/var/www/html
        networks:
            - laravel
